const theme = {
  ModalBackground: "rgba(0, 0, 0, 0.3)",
  GulfBlue: "#39425c",
  Solitude: "#eaf1ff",
  Mischka: "#9b9eab",
  PictonBlue: "#69a3db",
  Whisper: "#EBEBEB",
  Snow: "#FBFBFB",
  AliceBlue: "#EAF3FA",
  DodgerBlue: "#1B9CFC",
  LinkWater: "#c4cad7",
  Gossamer: "#3aab83",

  // ItemHoverGreen: "#D7F1EA",
  ItemColor: "#e0e5ee",
  ItemHoverColor: "#f5f5f5",
  ProjectPageBorderBottom: "#bec3cc",

  DetailPageBlue: "#D7E7F6",
  ButtonGreen: "#2BC7A3",
  ButtonPink: "#FF928B",
  TotalResultPageButtonGreen: "#10ac84",
  StatusMenuGreen: "#10ac84",
  MainYellow: "#FFB100",

  BabyPowder: "#f9f8f5",
  Aero: "#76b9e4",
  LittleBoyBlue: "#69A3DB",
  SpanishBlue: "#2c72b5",
  OrangeYelloCrayola: "#efcb68",
  InterviewModalBorder: "#B0AFAD",
  InterviewModalContent: "#666563",
  LittleBoyBlueDark: "#4f8dc6",
  LittleBoyBlueDeepDark: "#3677b5",
  CircleButtonGray: "#5D5F5F",
  QuestionContentGray: "#5D5F5F",
  white: "#ffffff",
  Black: "#000000",
};

export default theme;
