export const RECORD_STATE_TYPE = {
  INTERVIEW_BEFORE: 0,
  QUESTION_BEFORE: 1,
  QUESTIONING: 2,
  ANSWER_BEFORE: 3,
  ANSWERING: 4,
  SAVING: 5,
};

export const BUTTON_NAME = {
  [RECORD_STATE_TYPE.INTERVIEW_BEFORE]: "면접 시작",
  [RECORD_STATE_TYPE.QUESTION_BEFORE]: "질문 하기",
  [RECORD_STATE_TYPE.QUESTIONING]: "질문 종료",
  [RECORD_STATE_TYPE.ANSWER_BEFORE]: "답변 하기",
  [RECORD_STATE_TYPE.ANSWERING]: "답변 완료",
  [RECORD_STATE_TYPE.SAVING]: "저장 중...",
};
